vars:
  dotfiles_repo: "git@github.com:path/to/your/repo"
  dotfiles_repo_version: master
  dotfiles_repo_local_destination: "path/to/your/destination"
  dotfiles_files:
      - .gitconfig
      - .zshrc
